name: Verify: Run E2E Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  verify:
    name: Verify E2E Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Start application and run tests
      run: |
        # Start the server in background
        npm start &
        
        # Wait for server to be ready with retries
        echo "Waiting for server to start..."
        for i in {1..15}; do
          if curl -s -f http://localhost:3000 > /dev/null 2>&1; then
            echo "Server is ready after $i attempts!"
            break
          fi
          echo "Attempt $i: Server not ready yet, waiting..."
          sleep 3
        done
        
        # Final check - if server is not ready, exit
        if ! curl -s -f http://localhost:3000 > /dev/null 2>&1; then
          echo "ERROR: Server failed to start after 15 attempts"
          exit 1
        fi
        
        echo "Server is running successfully. Starting Cypress tests..."
        
        # Run Cypress tests
        npx cypress run --browser chrome --headless
        
        # Cleanup
        pkill -f "http-server" || true
        
    - name: Upload screenshots (if any)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress/screenshots/
        if-no-files-found: ignore
        
    - name: Upload videos (if any)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: cypress/videos/
        if-no-files-found: ignore