name: Verify: Run E2E Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  verify:
    name: Verify E2E Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Start application and run tests
      run: |
        # Start the server in background
        npm start &
        
        # Wait for server to be ready
        echo "Waiting for server to start..."
        for i in {1..30}; do
          if curl -s http://localhost:3000 > /dev/null; then
            echo "Server is ready!"
            break
          fi
          echo "Attempt $i: Server not ready yet, waiting..."
          sleep 2
        done
        
        # Verify server is running
        if ! curl -s http://localhost:3000 > /dev/null; then
          echo "Server failed to start"
          exit 1
        fi
        
        # Run Cypress tests
        echo "Running Cypress tests..."
        npx cypress run --browser chrome --headless
        
        # Cleanup
        pkill -f "http-server" || true