name: Verify: Run E2E Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  verify:
    name: Verify E2E Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify: Run Cypress tests
      uses: cypress-io/github-action@6
      with:
        browser: chrome
        record: false
        start: npm start
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 120