name: Verify: Run E2E Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  verify:
    name: Verify E2E Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Start application
      run: |
        npm start &
        sleep 5
        curl -f http://localhost:3000 || exit 1
        
    - name: Wait for application to start
      run: npx wait-on http://localhost:3000 --timeout 60000
      
    - name: Verify: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        record: false
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 120